version: '3.8'

networks:
  data_network:
    driver: bridge

services:
  minio:
    image: minio/minio:latest
    container_name: datalake_minio
    ports:
      - "9000:9000" 
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "senha123"
    command: server /data --console-address ":9001"
    networks:
      - data_network
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:13
    container_name: warehouse_postgres
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "senha123"
      POSTGRES_DB: "gold_db"
    ports:
      - "5432:5432"
    networks:
      - data_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jupyter:
    build: .  
    container_name: processing_jupyter
    ports:
      - "8888:8888"
    environment:
      DL_ENDPOINT: "http://minio:9000"
      DL_ACCESS_KEY: "admin"
      DL_SECRET_KEY: "senha123"
      DB_HOST: "postgres"
      DB_NAME: "gold_db"
      DB_USER: "user"
      DB_PASS: "senha123"
    volumes:
      - ../src:/home/jovyan/work/src           
      - ../notebooks:/home/jovyan/work/notebooks 
      - ../datasets:/home/jovyan/work/datasets   
    networks:
      - data_network
    depends_on:
      - minio
      - postgres
  metabase:
    image: metabase/metabase:latest
    container_name: viz_metabase
    ports:
      - "3000:3000"
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    networks:
      - data_network
    volumes:
      - metabase_data:/metabase-data
    depends_on:
      - postgres

volumes:
  minio_data:
  postgres_data:
  metabase_data: